prefer-workspace-packages: true
packages:
  # all packages in subdirs of packages/ and components/
  - 'blockchain'
  - 'website'
  # - 'packages/**'
  # - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
