prefer-workspace-packages: true
packages:
  # all packages in subdirs of packages/ and components/
  - "apps/**"
  # - 'packages/**'
  # - 'components/**'
  # exclude packages that are inside test directories
  - "!**/test/**"
